modLoader = "javafml"
issueTrackerURL = "https://github.com/kawaiicakes/IceBoatNerfReforged/issues"
loaderVersion = "${loader_version_range}"
license = "MIT"

[[mods]]
modId = "iceboatnerf"
version = "${mod_version}"
displayName = "Ice Boat Nerf"
authors = "${mod_authors}"
description = "${mod_description}"
logoFile = "iceboatnerf.png"

[[dependencies.iceboatnerf]]
modId = "forge"
mandatory = true
versionRange = "${forge_version_range}"
ordering = "NONE"
side = "SERVER"

[[dependencies.iceboatnerf]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "SERVER"